# helm pull grafana/grafana --untar --untardir ./Charts --version 9.2.9

# Dashboard-Link: https://grafana.com/grafana/dashboards/20568-opentelemetry-dotnet-webapi/ rev6

# grafana-values.yaml
replicas: 1

# Image
image:
  repository: grafana/grafana
  tag: 11.0.0 
  pullPolicy: IfNotPresent

# Service
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

# Credentials
adminUser: admin
adminPassword: admin123

# Data sources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
          lokiSearch:
            datasourceUid: loki
          serviceMap:
            datasourceUid: prometheus