# helm repo add grafana https://grafana.github.io/helm-charts
# helm repo update
# helm pull grafana/loki --untar --untardir ./Charts --version 6.30.1
  
# helm template grafana/loki \
# --namespace default \
# --values loki_values.yaml \
# > loki_service.yaml

# Image
global:
  image:
    repository: grafana/loki
    tag: latest
    pullPolicy: IfNotPresent
    
# Setting a name    
fullnameOverride: loki
deploymentMode: SingleBinary  # Single instance

# Required to disable pods
test:
  enabled: false

# loki-values.yaml
loki:
  
  # Otherwhise test schema error
  useTestSchema: true
  
  # Storage config to choose the local filesystem
  config: |-
    auth_enabled: false
    server:
      http_listen_port: 3100
    common:
      path_prefix: /tmp/loki
      storage:
        filesystem:
          chunks_directory: /tmp/loki/chunks
          rules_directory: /tmp/loki/rules
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
    
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
        - from: 2024-02-14  # Heutiges Datum als Startzeitpunkt
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    
    ruler:
      alertmanager_url: http://localhost:9093
    
    analytics:
      reporting_enabled: false
    
    limits_config:
      volume_enabled: true
      allow_structured_metadata: true

# Single binary instance
singleBinary:
  
  replicas: 1
  
  # Find chart generated loki config file
  extraArgs:
    - "--config.file=/etc/loki/config.yaml"

  # In volume/Path
  extraVolumes:
    - name: loki-config
      configMap:
        name: loki # Chart generated name, from the overrideName
        items:
          - key: config.yaml
            path: config.yaml
  extraVolumeMounts:
    - name: loki-config
      mountPath: /etc/loki
      readOnly: true
      
  # Disable persistence
  persistence:
    enabled: false

  # Readinessprobe, theres no livenessprobe
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3

# Deactivate all other pods and components
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
distributor:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
frontend:
  replicas: 0
gateway:
  replicas: 0
overridesExporter:
  replicas: 0
frontendWorker:
  replicas: 0
queryScheduler:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
  
sidecar:
  rules:
    enabled: false
    
memcachedExporter:
  enabled: false
  
lokiCanary:
  enabled: false
  
resultsCache:
  enabled: false
  
chunksCache:
  enabled: false

