
# helm template opentelemetry-collector \
#  ./Charts/opentelemetry-collector \
#  --namespace default \
#  --values otel_collector_values.yaml \
#  > otel_collector_service.yaml

nameOverride: otel-collector
fullnameOverride: otel-collector

# otel_collector_values.yaml
mode: deployment
replicaCount: 1

image:
  repository: otel/opentelemetry-collector
  tag: latest

configMap:
  create: false
  existingName: otel-collector-configmap

# ports als Map, nicht als Liste!
ports:
  otlp:
    enabled: true
  otlp-http:
    enabled: true
  jaeger-compact:
    enabled: false
  jaeger-thrift: 
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
  metrics:
    enabled: true
    containerPort: 9201
    servicePort: 9201
    protocol: TCP

# Init containers
initContainers:
  - name: wait-for-deps
    image: curlimages/curl:8.8.0
    command:
      - sh
      - -c
      - |
        set -e
        for url in \
          http://tempo:3200/ready \
          http://prometheus:9090/-/ready \
          http://loki:3100/ready
        do
          echo "Waiting for $url ..."
          until curl -sf "$url" >/dev/null; do
            sleep 5
          done
        done
        echo "All back‑ends are ready."

# Extra containers/sidecars for checks
extraContainers:
  - name: otel-collector-healthcheck
    image: curlimages/curl:latest
    command:
      - sh
      - -c
      - |
        until curl -sf http://localhost:13133; do sleep 2; done
        tail -f /dev/null
    readinessProbe:
      httpGet:
        path: /
        port: 13133
      initialDelaySeconds: 5
      periodSeconds: 5