# Deploy via: kubectl apply -f otel_collector_configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-configmap
data:
  relay: |
    extensions:
        health_check:
          endpoint: "0.0.0.0:13133"
  
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
  
    exporters:
      debug:
        verbosity: detailed
      prometheus:
        endpoint: 0.0.0.0:9201
        send_timestamps: true
        metric_expiration: 180m
        enable_open_metrics: true
        resource_to_telemetry_conversion:
          enabled: true
      otlp:
        endpoint: tempo:4317
        tls:
          insecure: true
      otlphttp:
        endpoint: "http://loki:3100/otlp"
  
    service:
      extensions: [ health_check ]
      telemetry:
        logs:
          level: "debug"
      pipelines:
        traces:
          receivers: [ otlp ]
          exporters: [ debug, otlp ]
        metrics:
          receivers: [ otlp ]
          exporters: [ debug, prometheus ]
        logs:
          receivers: [ otlp ]
          exporters: [ debug, otlphttp ]
