# helm template prometheus \
#  ./Charts/prometheus \
#  --namespace default \
#  --values prometheus_values.yaml \
#  > prometheus_service.yaml

# prometheus_values.yaml
server:
  enabled: true

  # Change service name
  fullnameOverride: prometheus
  
  # No storage for now
  persistentVolume:
    enabled: false
  
  # Service 
  service:
    type: NodePort # ClusterIp for prod
    servicePort: 9090
    targetPort: 9090  # Disable for prod
  
  # Service settings
  prometheusSpec:
    replicas: 1
    image:
      repository: prom/prometheus
      tag: latest

    # Health check
    livenessProbe:
      httpGet:
        path: /
        port: 9090
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 3
      
    readinessProbe:
      httpGet:
        path: /
        port: 9090
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 3

# Other included pods
alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false

# Scraping otel-collector data, 5 seconds is important, otherwhise we lose data!
serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'otel'
        metrics_path: /metrics
        scrape_interval: 5s
        static_configs:
          - targets: ['otel-collector:9201']