# helm repo add grafana https://grafana.github.io/helm-charts
# helm repo update
# helm pull grafana/Tempo --untar --untardir ./Charts --version 1.23.2
  
# helm template grafana/tempo \
# --namespace default \
# --values tempo_values.yaml \
# > tempo_service.yaml
  
# Change service name to tempo
fullnameOverride: tempo

# tempo_values.yaml as single binary
# Docker image & Tag
tempo:
  repository: grafana/tempo
  tag: latest

# Ports und Service
service:
  type: ClusterIP
  ports:
    - name: query
      port: 3200
      targetPort: 3200
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318

env: []

# Command Override to find the tempo config
extraArgs:
  - "-config.file=/etc/tempo.yml"

# Config for tempo
config: |-
  auth_enabled: false

  server:
    http_listen_port: 3200
  
  distributor:
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317
  
  storage:
    trace:
      backend: local
      wal:
        path: /tmp/tempo/wal
      local:
        path: /tmp/tempo/blocks
  
  compactor:
    compaction:
      compaction_window: 24h

# Persistence, save local
persistence:
  annotations: {}
  enabled: true
  enableStatefulSetAutoDeletePVC: false
  accessModes:
    - ReadWriteOnce
  size: 10Gi